name: arch_sherpa
description: Arch Sherpa â€” Part of the Flutter Sherpa Suite. Opinionated architecture scaffolding for Flutter projects.
version: 0.1.0
homepage: https://github.com/CarlosFAdev/arch_sherpa
repository: https://github.com/CarlosFAdev/arch_sherpa
issue_tracker: https://github.com/CarlosFAdev/arch_sherpa/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  args: ^2.7.0
  yaml: ^3.1.3
  path: ^1.9.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.26.3
  coverage: ^1.15.0

executables:
  arch_sherpa: arch_sherpa
