name: arch_sherpa
description: CLI for architecture scaffolding and structure validation in Flutter projects.
version: 0.2.2
homepage: https://github.com/CarlosFAdev/arch_sherpa
repository: https://github.com/CarlosFAdev/arch_sherpa
issue_tracker: https://github.com/CarlosFAdev/arch_sherpa/issues
topics:
  - flutter
  - dart
  - cli
  - architecture
  - scaffolding

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.1.0
  test: ^1.26.3

executables:
  arch_sherpa: arch_sherpa
